export { LessonPlayer, type LessonPlayerProps } from "./LessonPlayer";
export { DefaultStage } from "./DefaultStage";
export { RealStage, realStage } from "./RealStage";
export { PlayerControls } from "./PlayerControls";
export { useLessonPlayer, type PlayerOptions } from "./useLessonPlayer";
export { LessonEngine, type PlayerState } from "./engine";
export { COACH_ID_KINDS, coachId, findCoachTarget } from "./ids";
export { defaultProgressStore } from "./progress";
export { labClock, realClock, createTestClock, type Clock, type TestClock } from "./clock";
export type { EditVia, LiveView, Stage, StageControl, StageControls, StageProps, StageScene } from "./types";
