// The inline script of index.html, generated so its lists of themes and modes cannot drift from the
// app: `npm run theme:css -w web` rewrites the region between the markers; a spec and the build's
// prebuild step fail when it is stale.
import { LAST_KEY, MODE_PREFERENCES, SETTINGS_PREFIX, USER_KEY } from "../settings";
import { THEMES } from "./palette";

export const INIT_START = "<!-- theme-init:start -->";
export const INIT_END = "<!-- theme-init:end -->";

export function themeInitScript(): string {
  const list = (values: readonly string[]) => JSON.stringify(values);
  return `${INIT_START}
    <script>
      // Generated by web/scripts/generate-theme-css.ts (src/theme/initScript.ts). Do not edit by hand.
      // Applies the student's color theme and mode before first paint, so a reload never flashes the
      // wrong palette. The session's user (if known) decides whose settings apply; otherwise the last
      // appearance used in this browser does.
      (function () {
        var root = document.documentElement;
        var theme = ${JSON.stringify(THEMES[0])};
        var mode = "system";
        try {
          var user = sessionStorage.getItem(${JSON.stringify(USER_KEY)});
          var stored = JSON.parse(localStorage.getItem(user ? ${JSON.stringify(SETTINGS_PREFIX)} + user : ${JSON.stringify(LAST_KEY)}) || "null");
          var found = (user ? stored && stored.appearance : stored) || {};
          if (${list(THEMES)}.indexOf(found.theme) >= 0) theme = found.theme;
          if (${list(MODE_PREFERENCES)}.indexOf(found.mode) >= 0) mode = found.mode;
        } catch (e) {
          /* damaged or unavailable storage: the defaults apply */
        }
        var dark = mode === "dark";
        if (mode === "system") {
          try {
            dark = matchMedia("(prefers-color-scheme: dark)").matches;
          } catch (e) {
            dark = false;
          }
        }
        root.setAttribute("data-theme", theme);
        root.setAttribute("data-mode", dark ? "dark" : "light");
        root.classList.toggle("dark", dark);
      })();
    </script>
    ${INIT_END}`;
}

/** `html` with the region between the markers replaced by the current script. */
export function withThemeInit(html: string): string {
  const start = html.indexOf(INIT_START);
  const end = html.indexOf(INIT_END);
  if (start < 0 || end < 0) throw new Error("index.html lacks the theme-init markers");
  return html.slice(0, start) + themeInitScript() + html.slice(end + INIT_END.length);
}
